name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  MAVEN_OPTS: -DskipTests=false

jobs:
  build:
    name: build 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------------------
      # Backend
      # ---------------------------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Cache ~/.m2
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build and run backend tests (Maven)
        run: mvn -B clean test package

      - name: Upload backend test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-target
          path: target/

      # ---------------------------
      # Frontend + Node
      # ---------------------------
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint --if-present

      - name: Build frontend (if build script exists)
        run: npm run build --if-present

      - name: Run unit tests (Mocha)
        run: npm test --if-present

      - name: Run BDD tests (Cucumber)
        run: npm run bdd --if-present

      - name: Upload frontend build (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ./dist
          if-no-files-found: ignore
