name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Unit Tests
      - name: Run Unit Tests
        run: npm run test:unit

      # Run API Tests
      - name: Run API Tests
        run: npm run test:api

      # Run Selenium UI Tests
      - name: Run UI Tests
        run: |
          # Install Chrome & Chromedriver
          sudo apt-get update
          sudo apt-get install -y xvfb chromium-browser
          export CHROME_BIN=/usr/bin/chromium-browser
          npm run test:ui
